on:
   workflow_run:
     workflows: ["CI to Docker Hub"]
     branches: [main]
     types:
       - completed

jobs:
 run-aci:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Docker Compose CLI
            run: >
              curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh

    - name: "login azure"
       run: "docker login azure --client-id $AZURE_CLIENT_ID --client-secret $AZURE_CLIENT_SECRET --tenant-id $AZURE_TENANT_ID"
       env:
       AZURE_TENANT_ID: '${{ secrets.AZURE_TENANT_ID }}'
       AZURE_CLIENT_ID: '${{ secrets.AZURE_CLIENT_ID }}'
       AZURE_CLIENT_SECRET: '${{ secrets.AZURE_CLIENT_SECRET }}'

    - name: "Create an aci context"
       run: 'docker context create aci --subscription-id $AZURE_SUBSCRIPTION_ID --resource-group Docker --location southindia acicontext'
       env:
       AZURE_SUBSCRIPTION_ID: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'

    - name: "Run my App"
       run: 'docker --context acicontext run -d --name discovery --domainname discovery -p 8085:8085 steveferns/discovery'

    - name: "Test deployed server"
       run: 'curl http://discovery.southindia.azurecontainer.io/'
